# enter trial defaults if necessary
# these will be saved for all experiments unless they are deleted
# ex. 
# strain: Dl
# sex: female
strain: DL
sex: female
experimenter:
date: 2023-07-05
starvation-start: 2023-07-05 11:00:00